services:
  bastion-server:
    container_name: bastion-server
    build:
      context: .
      dockerfile: bastion-server/Dockerfile
    environment:
      BASTION_SERVER_PUBLIC_KEY: ${BASTION_SERVER_PUBLIC_KEY:-}
    ports:
      - "8080:8080"
    restart: unless-stopped
